### ISSUE TITLE
Support for `tvos targets`

### ISSUE THREAD

**Issue by ScottPierce** [ReactiveCircus/cache4k#11]
Please add support for the various tvos targets as well

tvosArm64
tvosSimulatorArm64
tvosX64

**Comment by ScottPierce** [comment]
I created a PR to solve this and unblock me here - https://github.com/ReactiveCircus/cache4k/pull/12

**Comment by ychescale9** [comment]
Thanks! I'll do a release next week.

**Comment by ScottPierce** [comment]
@ychescale9 Any chance this could happen sooner? This is blocking me.

**Comment by ychescale9** [comment]
Can you use snapshot for now?😀 I'm on a trip this week.
Also are you using compose in the same project? If so I cant release with Kotlin 1.6.10 until it's supported.

**Comment by ychescale9** [comment]
Just released 0.4.0. Thanks for the contribution 😃

**Comment by ScottPierce** [comment]
Thank you!
