### ISSUE TITLE
KMM New Memory Model

### ISSUE THREAD

**Issue by dcvz** [ReactiveCircus/cache4k#16]
@ychescale9 I see that you enabled the new memory model in a previous commit. Do you plan to only support the new memory model in the future or do you wish to support both?

In the new memory model there would no longer be a need for IsoMap. Just safe concurrent access.

I'd be happy to work on an implementation if you let me know which route you were intending to take.

**Comment by ychescale9** [comment]
I originally planned to only support new mm but if it's not too much effort to support both until new mm is stable that'd be better😀

I assume we just need to check the isNewMM flag in stdlib?

Super happy to accept PRs!

**Comment by dcvz** [comment]
The most basic support would be enough to just check the `isNewMM` and then use a regular map or an isoMap depending on the case.. but there's probably other optimizations that could be made.

I'll have a look and see if we can do easy support for both without compromising the benefits of of the new MM.

**Comment by dcvz** [comment]
Closing this as PR addressing this has been merged
