### ISSUE TITLE
Caching get clear after exit app

### ISSUE THREAD

**Issue by rameshvoltella** [ReactiveCircus/cache4k#21]
Hi,
 put and get caching is working for the first time but when the user exits app and tries to get cache data it prints null.

Am using koltin
`      
           val cache = Cache.Builder()
            .expireAfterAccess(1.minutes).build<Long, String>()

           saveValue.setOnClickListener { cache.put(1,"kona") }

        getValue.setOnClickListener { Log.d("value",""+cache?.get(1)) }`

Any info more needed I will provide

**Comment by ychescale9** [comment]
Hi, this library is an in-memory cache which means data won't be persisted to disk and therefore won't survive app restart. For persistent cache you have Room, SQLDelight, DataStore and plenty of other options.
