### ISSUE TITLE
Publication of FakeTimeSource

### ISSUE THREAD

**Issue by ho2ri2s** [ReactiveCircus/cache4k#29]
I would like to unit test the cache expiration time.
We would be happy if users could also reuse the FakeTimeSource mentioned in the documentation!
Do you plan to release a set of classes related to testing, including FakeTimeSource?

https://github.com/ReactiveCircus/cache4k#unit-testing-cache-expirations

**Comment by ychescale9** [comment]
`FakeTimeSource` was removed in [this change](https://github.com/ReactiveCircus/cache4k/pull/20) which renamed `fakeTimeSource(...)` to `timeSource(...)`. I think we can move the `FakeTimeSource` implementation from unit test back to the library. Happy to review a PR 😃

**Comment by ho2ri2s** [comment]
Thanks for the reply.
I've created a [PR](https://github.com/ReactiveCircus/cache4k/issues/29) and would be happy to review it.
