### ISSUE TITLE
Crash at Runtime Startup

### ISSUE THREAD

**Issue by Shabinder** [ReactiveCircus/cache4k#5]
Hey , Thanks for your work, I am interested in using your Lib in one of my projects : [SpotiFlyer](https://github.com/Shabinder/SpotiFlyer),
But unfortunately, It crashes as Runtime.
```
java.lang.NoSuchMethodError: No virtual method getINFINITE-UwyO8pc()D in class Lkotlin/time/Duration$Companion; or its super classes (declaration of 'kotlin.time.Duration$Companion' appears in /data/data/com.shabinder.spotiflyer/code_cache/.overlay/base.apk/classes3.dex)
        at io.github.reactivecircus.cache4k.CacheBuilderImpl.<init>(Cache.kt:109)
        at io.github.reactivecircus.cache4k.Cache$Builder$Companion.newBuilder(Cache.kt:99)
```

**Comment by Shabinder** [comment]
Maybe This Could help: https://github.com/chrisbanes/Store/commit/1ddf5e681839aa9354ddaac594801beacbd78315

**Comment by ychescale9** [comment]
Yes the duration APIs are often binary incompatible in different Kotlin versions. I've updated to Kotlin 1.5 and I'll do a new release soon so once you are able to update to Kotlin 1.5 (you'll probably have to wait a bit as you're using compose) it should work:)

**Comment by Shabinder** [comment]
Do a release with kotlin 1.4.32 too , as compose-desktopbis compatible with kotlin 1.4.32 only yet

**Comment by Shabinder** [comment]
@ychescale9 I cloned and built your lib with Kotlin 1.4.32 same as the project, but still getting the same error: 
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/44765050/117299243-ef1dcd80-ae95-11eb-9c97-794e4f67e86a.png">

**Comment by Shabinder** [comment]
For now, I will copy the sources and use in the project, will change to **lib** when compose is compatible with Kotlin 1.5

**Comment by ScottPierce** [comment]
@ychescale9 when is the new release coming? I'm blocked by this currently.

**Comment by ychescale9** [comment]
Sorry for the wait, I'll try to do a release tomorrow.

**Comment by ychescale9** [comment]
0.2.0 has been released. Please let me know if this works with Kotlin 1.5.0 :)
